### ISSUE TITLE
Saint Lucia data has a comma separated string for timeseries-byLocation.json on 07/27

### ISSUE THREAD

**Issue by nateyoder** [covidatlas/li#353] opened 2020-07-27 17:44 UTC
* **Source: ** https://coronadatascraper.com/#timeseries-byLocation.json
* **File: ** timeseries-byLocation.json
* **Issue: ** The cases, deaths, recovered, and tested fields are all strings for dates 07-11 through 07-27:

```
"2020-07-11": {
        "cases": "22",
        "deaths": "0",
        "recovered": "2196,397,230",
        "tested": "2,022",
        "growthFactor": 1
      },
      "2020-07-12": {
        "cases": "22",
        "deaths": "0",
        "recovered": "2196,540,222",
        "tested": "2,022",
        "growthFactor": 1
      },
      "2020-07-13": {
        "cases": "22",
        "deaths": "0",
        "recovered": "2196,669,879",
        "tested": "2,048",
        "growthFactor": 1
      },
      "2020-07-14": {
        "cases": "22",
        "deaths": "0",
        "recovered": "2196,780,428",
        "tested": "2,082",
        "growthFactor": 1
      },
      "2020-07-15": {
        "cases": "22",
        "deaths": "0",
        "recovered": "2196,884,151",
        "tested": "2,111",
        "growthFactor": 1
      },
      "2020-07-16": {
        "cases": "23",
        "deaths": "0",
        "recovered": "2197,016,851",
        "tested": "2,134",
        "growthFactor": 1.05
      },
      "2020-07-17": {
        "cases": "23",
        "deaths": "0",
        "recovered": "2197,154,840",
        "tested": "2,140",
        "growthFactor": 1
      },
      "2020-07-18": {
        "cases": "23",
        "deaths": "0",
        "recovered": "2197,154,840",
        "tested": "2,140",
        "growthFactor": 1
      },
      "2020-07-19": {
        "cases": "23",
        "deaths": "0",
        "recovered": "2197,377,183",
        "tested": "2,155",
        "growthFactor": 1
      },
      "2020-07-20": {
        "cases": "23",
        "deaths": "0",
        "recovered": "2197,377,183",
        "tested": "2,155",
        "growthFactor": 1
      },
      "2020-07-21": {
        "cases": "23",
        "deaths": "0",
        "recovered": "2197,702,075",
        "tested": "2,370",
        "growthFactor": 1
      },
      "2020-07-22": {
        "cases": "23",
        "deaths": "0",
        "recovered": "2197,811,127",
        "tested": "2,412",
        "growthFactor": 1
      },
      "2020-07-23": {
        "cases": "24",
        "deaths": "0",
        "recovered": "2227,948,513",
        "tested": "2,472",
        "growthFactor": 1.04
      },
      "2020-07-24": {
        "cases": "24",
        "deaths": "0",
        "recovered": "2228,121,700",
        "tested": "2,597",
        "growthFactor": 1
      },
      "2020-07-25": {
        "cases": "24",
        "deaths": "0",
        "recovered": "2228,292,311",
        "tested": "2,934",
        "growthFactor": 1
      },
      "2020-07-26": {
        "cases": "24",
        "deaths": "0",
        "recovered": "2228,292,311",
        "tested": "2,934",
        "growthFactor": 1
      },
      "2020-07-27": {
        "cases": "24",
        "deaths": "0",
        "recovered": "2228,292,311",
        "tested": "2,934",
        "growthFactor": 1
      },
      "2020-07-28": {
        "cases": 24,
        "deaths": 0,
        "recovered": 22,
        "growthFactor": 1
      }
```

**Comment by jzohrab** [comment] 2020-07-30 20:12
Thanks @nateyoder , checking.

**Comment by stevenganz** [comment] 2020-08-03 22:58
Also, rows for St. Lucia including 73,568 are similarly wrong ("2196,397,230") in timeseries.csv.

**Comment by jzohrab** [comment] 2020-08-04 01:13
Hm, the source for St Lucia (in `src/shared/sources/lc`) is hitting https://www.covid19response.lc/ ... looking at that page, everything looks fine, but running the source locally is returning trash:

```
MacBook-Air:li jeff$ ./start --crawl lc
MacBook-Air:li jeff$ ./start --scrape lc

┌─────────┬────────────┬──────────────┬───────┬────────┬─────────┬────────────────┐
│ (index) │ locationID │     date     │ cases │ deaths │ tested  │   recovered    │
├─────────┼────────────┼──────────────┼───────┼────────┼─────────┼────────────────┤
│    0    │ 'iso1:lc'  │ '2020-08-03' │ '25'  │  '0'   │ '3,548' │ '2229,630,598' │
└─────────┴────────────┴──────────────┴───────┴────────┴─────────┴────────────────┘
```

Looking into a fix, cheers! jz

**Comment by stevenganz** [comment] 2020-08-04 01:21
That's a lot of recoveries for 25 cases!

**Comment by jzohrab** [comment] 2020-08-04 01:21
The code is erroneously joining the numbers from "Number of COVID-19 Repatriations from Saint Lucia" (2), "Number of Persons Recovered from COVID-19" (22), and "Number of Confirmed Cases of COVID-19 in the Americas" (9,630,598)  ... :-(   

The code would have been correct at one point, but the source data page has changed.  Needs a fix to select the right stuff.

**Comment by jzohrab** [comment] 2020-08-04 01:58
I've merged a fix into master (ref https://github.com/covidatlas/li/pull/372), but this won't show up fixed in prod until I fix https://github.com/covidatlas/li/issues/368 -- we need to change how we launch code :-)

Thanks, I'll keep this issue and see that it's launched.

**Comment by stevenganz** [comment] 2020-08-04 02:14
Thanks for the quick action! 

Steve

**Comment by jzohrab** [comment] 2020-08-04 02:28
This one was simple ... there are tons of other issues requiring more head scratching.  Thanks to you and @nateyoder for the check.  We really need to get data quality monitoring in place!!!  👋

**Comment by jzohrab** [comment] 2020-08-04 12:39
Should be in production now, will keep this open until it's checked there.  @nateyoder or @stevenganz , if this clears up, please close the ticket.

**Comment by stevenganz** [comment] 2020-08-10 18:57
Hi JZ, 

Any idea when this will be reflected in the downloadable files (timeseries.csv.zip)? 

Steve

**Comment by jzohrab** [comment] 2020-08-10 19:27
It’s not there now?  Should be!

**Comment by stevenganz** [comment] 2020-08-10 20:46
I'm still getting bad values for St. Lucia. Please check yourself.

**Comment by jzohrab** [comment] 2020-08-10 21:59
I’ll check generation status and the data when I have a better connection.
Thx!

**Comment by jzohrab** [comment] 2020-08-11 14:17
I didn't check the report, but I edited the data in prod manually.

We don't yet have a process to correct historical data -- it's not as straightforward as one would think.  There's an open issue.

@stevenganz LMK if this is resolved.  I'm not easily able to check due to my _extremely_ limited data bandwidth.  Cheers! z

**Comment by stevenganz** [comment] 2020-08-16 09:09
Thanks and sorry for the delay in responding. The numbers look more reasonable now, but still contain commas for dates prior to 8/4. I'd appreciate if you could remove those.

**Comment by jzohrab** [comment] 2020-08-16 20:02
Strange, I'm sure I edited everything!  Not saying you're wrong, am saying that perhaps it was subsequently updated ... not sure why though.  Double-checking prod tables now.  Thanks for checking @stevenganz

**Comment by jzohrab** [comment] 2020-08-16 20:12
Ah, I was only looking at the terrible "recovered" numbers.  I'm removing commas in "tested" now, assuming that's the field you meant.

**Comment by jzohrab** [comment] 2020-08-16 20:16
OK, hopefully that's all the commas you can see for St Lucia, @stevenganz .  In a day-ish, let me know if all is as expected.  Thanks again, jz

**Comment by stevenganz** [comment] 2020-08-17 09:57
Looks good now, @jzohrab. Thanks! Yes, the commas were in the tested column -- sorry for any confusion.

**Closed** 2020-08-17 15:39 UTC
Labels: needs-verification
